import fs from 'fs';
import path from 'path';

import { getAppDirectory } from './discovery';

// The dev-server bootstrap, generated per build so it can import an optional
// app-owned overrides file (apps/<app>/devServer.config.ts, default-exporting
// DevServerConfigOverrides). The `quidproquo-dynamic-loader` import is a
// virtual module injected by QpqPlugin at bundle time. QPQ_WEB_ROOT (set in
// the docker platform image) turns on static views serving.
export const writeDevServerEntry = (root: string, appName: string): string => {
  const entryDir = path.join(root, 'dist', 'qpq', 'dev-server');
  const entryPath = path.join(entryDir, 'entry.ts');

  const overridesPath = path.join(getAppDirectory(appName), 'devServer.config.ts');
  const overridesImport = fs.existsSync(overridesPath)
    ? `import devServerConfigOverrides from ${JSON.stringify(overridesPath.replace(/\.ts$/, ''))};`
    : 'const devServerConfigOverrides = {};';

  fs.mkdirSync(entryDir, { recursive: true });
  fs.writeFileSync(
    entryPath,
    `// GENERATED by qpq — do not edit.
import { startDevServer } from 'quidproquo-dev-server';
import {
  qpqConfigs,
  qpqDynamicModuleLoaderForService,
  // @ts-ignore - Special build-time virtual module
} from 'quidproquo-dynamic-loader';

${overridesImport}

startDevServer(
  {
    serverDomain: 'localhost',
    serverPort: 8080,
    webSocketPort: 8888,
    // Scoped per app so running the dev server for two apps out of the same
    // repo root doesn't share kvs/file-storage/config state.
    runtimePath: ${JSON.stringify(path.join('.qpq-runtime', appName))},
    fileStorageConfig: {
      secureUrlSecret: 'dev-secure-url-secret',
    },
    qpqConfigs,
    dynamicModuleLoader: qpqDynamicModuleLoaderForService,
    webRoot: process.env.QPQ_WEB_ROOT,
    logServiceName: 'admin',
    delay: { default: 0 },
  },
  devServerConfigOverrides,
);
`,
  );

  return entryPath;
};
