import fs from 'fs';
import path from 'path';

import { getAppDirectory } from './discovery';

// TODO: This file is a mess, revisit and clean up.

// The dev-server bootstrap, generated per build so it can import an optional
// app-owned overrides file (apps/<app>/devServer.config.ts, default-exporting
// DevServerConfigOverrides). The `quidproquo-dynamic-loader` import is a
// virtual module injected by QpqPlugin at bundle time. QPQ_WEB_ROOT (set in
// the docker platform image) turns on static views serving.
// `startDevServer` runs forever; `runMigrations` does one pass and resolves. Both need the
// identical bundle — same configs, same dynamic loader — because the whole value of running
// migrations locally is that it rehearses the deployed path rather than a lookalike.
export type DevServerEntryMode = 'serve' | 'migrate';

export const writeDevServerEntry = (root: string, appName: string, mode: DevServerEntryMode = 'serve'): string => {
  const entryDir = path.join(root, 'dist', 'qpq', 'dev-server');
  const entryPath = path.join(entryDir, mode === 'migrate' ? 'migrate.entry.ts' : 'entry.ts');

  const overridesPath = path.join(getAppDirectory(appName), 'devServer.config.ts');
  const overridesImport = fs.existsSync(overridesPath)
    ? `import devServerConfigOverrides from ${JSON.stringify(overridesPath.replace(/\.ts$/, ''))};`
    : 'const devServerConfigOverrides = {};';

  fs.mkdirSync(entryDir, { recursive: true });
  fs.writeFileSync(
    entryPath,
    `// GENERATED by qpq — do not edit.
import { ${mode === 'migrate' ? 'runMigrations' : 'startDevServer'} } from 'quidproquo-dev-server';
import {
  qpqConfigs,
  qpqDynamicModuleLoaderForService,
  // @ts-ignore - Special build-time virtual module
} from 'quidproquo-dynamic-loader';

${overridesImport}

${mode === 'migrate' ? 'runMigrations' : 'startDevServer'}(
  {
    serverDomain: 'localhost',
    serverPort: 8080,
    webSocketPort: 8888,
    // Scoped per app so running the dev server for two apps out of the same
    // repo root doesn't share kvs/file-storage/config state.
    runtimePath: ${JSON.stringify(path.join('.qpq-runtime', appName))},
    fileStorageConfig: {
      secureUrlSecret: 'dev-secure-url-secret',
    },
    qpqConfigs,
    dynamicModuleLoader: qpqDynamicModuleLoaderForService,
    webRoot: process.env.QPQ_WEB_ROOT,
    logServiceName: 'admin',
    delay: { default: 0 },
  },
  devServerConfigOverrides,
)${
  mode === 'migrate'
    ? `
  .then((ran) => {
    const total = Object.values(ran).reduce((sum, keys) => sum + keys.length, 0);
    for (const [service, keys] of Object.entries(ran)) {
      for (const key of keys) {
        console.log(\` [\${service}] \${key}\`);
      }
    }
    console.log(total === 0 ? 'No pending migrations.' : \`Ran \${total} migration(s).\`);
    process.exit(0);
  })
  .catch((error) => {
    console.error('Migration failed:', error);
    // Non-zero so CI and shell chains actually notice.
    process.exit(1);
  })`
    : ''
};
`,
  );

  return entryPath;
};
