import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    'getting-started',
    'core-concepts',
    'use-cases',
    'architecture-overview',
  ],
  
  apiSidebar: [
    'api/index',
    {
      type: 'category',
      label: 'Config',
      items: [{type: 'autogenerated', dirName: 'config'}],
    },
    {
      type: 'category',
      label: 'Action Requesters',
      items: [{type: 'autogenerated', dirName: 'actions'}],
    },
  ],
};

export default sidebars;