// Rspack build for the QPQ local dev server.
//
// Workspace lib packages are aliased to their src/index.ts (see
// getWorkspaceSourceAliases) so rspack bundles them from source and watch mode
// picks up lib edits. QpqPlugin bundles every service's handlers and injects
// the `quidproquo-dynamic-loader` virtual module the entry imports.
import { QPQConfig, qpqCoreUtils } from 'quidproquo-core';

import path from 'path';
import { Configuration, ExternalItemFunctionData, IgnorePlugin } from '@rspack/core';

import { QpqPlugin } from '../plugins';
import { getWorkspaceSourceAliases } from './getWorkspaceSourceAliases';

export interface DevServerRspackOptions {
  // Consumer repo root (the directory holding package.json + apps/).
  root: string;
  // The dev-server entry file (the startDevServer bootstrap, e.g. generated by `qpq go:dev:api`).
  entry: string;
  // Every service config the dev server hosts.
  qpqConfigs: QPQConfig[];
}

export const getDevServerRspackConfig = ({ root, entry, qpqConfigs }: DevServerRspackOptions): Configuration => {
  const { aliases, packageNames } = getWorkspaceSourceAliases(root);

  // Dependency build quirks declared by any hosted service
  // (`defineBackendBundleOptions`) apply to the dev bundle too.
  const bundleOptions = qpqConfigs.map((qpqConfig) => qpqCoreUtils.getBackendBundleOptions(qpqConfig));
  const ignoreWarnings = bundleOptions.flatMap((options) => options.ignoreWarnings);
  const ignoreModules = bundleOptions.flatMap((options) => options.ignoreModules);

  // Don't bundle node_modules — require them at runtime instead. This keeps
  // native modules (sqlite3, sharp) and linked quidproquo packages loading from
  // their own install locations. Workspace packages and the
  // `quidproquo-dynamic-loader` virtual module are allowlisted so they get
  // bundled (from source, via the aliases above).
  const externaliseBarePackages = ({ request }: ExternalItemFunctionData, callback: (err?: Error, result?: string) => void): void => {
    const isBarePackage = !!request && !request.startsWith('.') && !request.startsWith('!') && !path.isAbsolute(request);
    const isBundled = !!request && (request === 'quidproquo-dynamic-loader' || packageNames.has(request));

    if (isBarePackage && !isBundled) {
      callback(undefined, `commonjs ${request}`);
      return;
    }

    callback();
  };

  return {
    entry,
    mode: 'development',
    target: 'node',
    devtool: 'source-map',

    output: {
      path: path.join(root, 'dist', 'qpq', 'dev-server'),
      filename: 'main.js',
      globalObject: 'this',
    },

    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.json'],
      alias: aliases,
    },

    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: /node_modules/,
          loader: 'builtin:swc-loader',
          options: {
            jsc: {
              parser: { syntax: 'typescript', tsx: false, decorators: true },
              transform: { legacyDecorator: true, decoratorMetadata: true },
              target: 'es2021',
            },
          },
        },
        {
          test: /\.tsx$/,
          exclude: /node_modules/,
          loader: 'builtin:swc-loader',
          options: {
            jsc: {
              parser: { syntax: 'typescript', tsx: true, decorators: true },
              transform: { legacyDecorator: true, decoratorMetadata: true },
              target: 'es2021',
            },
          },
        },
        {
          // JavaScript apps ship ESM-syntax .js inside type:commonjs packages;
          // 'auto' accepts both module syntaxes (the rspack default for files
          // outside a package "type" scope).
          test: /\.js$/,
          exclude: /node_modules/,
          type: 'javascript/auto',
        },
        {
          // Small fonts inline as data urls, larger ones emit as files.
          test: /\.(woff|woff2)$/,
          type: 'asset',
          parser: { dataUrlCondition: { maxSize: 4096 } },
        },
        // Templates imported as raw strings.
        { test: /\.html?$/, type: 'asset/source' },
        // Referenced txt/map assets emit as files.
        { test: /\.(txt|map)$/, type: 'asset/resource' },
      ],
    },

    externals: [externaliseBarePackages],

    ignoreWarnings: ignoreWarnings.map((ignoreWarning) => ({
      module: ignoreWarning.module ? new RegExp(ignoreWarning.module) : undefined,
      message: ignoreWarning.message ? new RegExp(ignoreWarning.message) : undefined,
    })),

    plugins: [
      new QpqPlugin({
        qpqConfigs,
        nodeModulePath: path.join(root, 'node_modules'),
        alwaysBundleStoryCode: true,
      }),
      ...ignoreModules.map(
        (ignoreModule) =>
          new IgnorePlugin({
            resourceRegExp: new RegExp(ignoreModule.resource),
            contextRegExp: ignoreModule.context ? new RegExp(ignoreModule.context) : undefined,
          }),
      ),
    ],

    watchOptions: { ignored: ['**/dist', '**/node_modules'] },
  };
};
