// Rspack build for the QPQ local dev server.
//
// Workspace lib packages are aliased to their src/index.ts (see
// getWorkspaceSourceAliases) so rspack bundles them from source and watch mode
// picks up lib edits. QpqPlugin bundles every service's handlers and injects
// the `quidproquo-dynamic-loader` virtual module the entry imports.
import { QPQConfig, qpqCoreUtils } from 'quidproquo-core';

import path from 'path';
import { Configuration, ExternalItemFunctionData, IgnorePlugin } from '@rspack/core';

import { getQpqCircularCheckPlugin, QpqPlugin } from '../plugins';
import { getWorkspaceSourceAliases } from './getWorkspaceSourceAliases';

export interface DevServerRspackOptions {
  // Consumer repo root (the directory holding package.json + apps/).
  root: string;
  // The dev-server entry file (the startDevServer bootstrap, e.g. generated by `qpq go:dev:api`).
  entry: string;
  // Every service config the dev server hosts.
  qpqConfigs: QPQConfig[];
}

export const getDevServerRspackConfig = ({ root, entry, qpqConfigs }: DevServerRspackOptions): Configuration => {
  const { aliases, packageNames } = getWorkspaceSourceAliases(root);

  // Dependency build quirks declared by any hosted service
  // (`defineBackendBundleOptions`) apply to the dev bundle too.
  const bundleOptions = qpqConfigs.map((qpqConfig) => qpqCoreUtils.getBackendBundleOptions(qpqConfig));
  const ignoreWarnings = bundleOptions.flatMap((options) => options.ignoreWarnings);
  const ignoreModules = bundleOptions.flatMap((options) => options.ignoreModules);

  // Don't bundle node_modules — require them at runtime instead. This keeps
  // native modules (e.g. sharp) and third-party deps loading from their real
  // install locations. Workspace packages, linked quidproquo packages and the
  // `quidproquo-dynamic-loader` virtual module are allowlisted so they get
  // bundled (from source, via the aliases above).
  //
  // Externals are resolved to absolute paths from the *requiring* module's
  // directory. Source-bundled linked packages live outside the consumer repo,
  // so a bare runtime require from the bundle would miss deps that only exist
  // in the framework repo's node_modules (e.g. quidproquo-dev-server's
  // body-parser); build-time resolution reproduces what node would have done
  // had the package not been bundled. Requests that don't resolve (optional
  // deps behind try/catch) fall back to a plain bare require.
  const externalResolutionCache = new Map<string, string>();

  const resolveExternal = (request: string, context: string): string => {
    const cacheKey = `${context}\n${request}`;
    const cached = externalResolutionCache.get(cacheKey);
    if (cached) {
      return cached;
    }

    let resolved = request;
    try {
      resolved = require.resolve(request, { paths: [context] });
    } catch {
      // Leave the bare request; the runtime require fails (or is caught by the
      // requiring package) exactly as it would without bundling.
    }

    externalResolutionCache.set(cacheKey, resolved);
    return resolved;
  };

  const externaliseBarePackages = ({ request, context }: ExternalItemFunctionData, callback: (err?: Error, result?: string) => void): void => {
    const isBarePackage = !!request && !request.startsWith('.') && !request.startsWith('!') && !path.isAbsolute(request);
    const isBundled = !!request && (request === 'quidproquo-dynamic-loader' || packageNames.has(request));

    if (isBarePackage && !isBundled) {
      callback(undefined, `commonjs ${resolveExternal(request, context || root)}`);
      return;
    }

    callback();
  };

  return {
    entry,
    mode: 'development',
    target: 'node',
    devtool: 'source-map',

    output: {
      path: path.join(root, 'dist', 'qpq', 'dev-server'),
      filename: 'main.js',
      globalObject: 'this',
    },

    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.json'],
      alias: aliases,
    },

    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: /node_modules/,
          loader: 'builtin:swc-loader',
          options: {
            jsc: {
              parser: { syntax: 'typescript', tsx: false, decorators: true },
              transform: { legacyDecorator: true, decoratorMetadata: true },
              target: 'es2021',
            },
          },
        },
        {
          test: /\.tsx$/,
          exclude: /node_modules/,
          loader: 'builtin:swc-loader',
          options: {
            jsc: {
              parser: { syntax: 'typescript', tsx: true, decorators: true },
              transform: { legacyDecorator: true, decoratorMetadata: true },
              target: 'es2021',
            },
          },
        },
        {
          // JavaScript apps ship ESM-syntax .js inside type:commonjs packages;
          // 'auto' accepts both module syntaxes (the rspack default for files
          // outside a package "type" scope).
          test: /\.js$/,
          exclude: /node_modules/,
          type: 'javascript/auto',
        },
        {
          // Small fonts inline as data urls, larger ones emit as files.
          test: /\.(woff|woff2)$/,
          type: 'asset',
          parser: { dataUrlCondition: { maxSize: 4096 } },
        },
        // Templates imported as raw strings.
        { test: /\.html?$/, type: 'asset/source' },
        // Referenced txt/map assets emit as files.
        { test: /\.(txt|map)$/, type: 'asset/resource' },
      ],
    },

    externals: [externaliseBarePackages],

    ignoreWarnings: ignoreWarnings.map((ignoreWarning) => ({
      module: ignoreWarning.module ? new RegExp(ignoreWarning.module) : undefined,
      message: ignoreWarning.message ? new RegExp(ignoreWarning.message) : undefined,
    })),

    plugins: [
      new QpqPlugin({
        qpqConfigs,
        nodeModulePath: path.join(root, 'node_modules'),
        alwaysBundleStoryCode: true,
      }),
      getQpqCircularCheckPlugin(),
      ...ignoreModules.map(
        (ignoreModule) =>
          new IgnorePlugin({
            resourceRegExp: new RegExp(ignoreModule.resource),
            contextRegExp: ignoreModule.context ? new RegExp(ignoreModule.context) : undefined,
          }),
      ),
    ],

    watchOptions: { ignored: ['**/dist', '**/node_modules'] },
  };
};
