// Regenerates apps/<app>/tsconfig.federated.json — the TypeScript path aliases
// for that app's cross-view federated imports
// (`@<app>/<svc>-service-views/<Thing>`). One file PER APP, inside the app
// folder — nothing app-specific lives at the repo root.
// This is the ONLY generated config: rspack computes exposes/remotes
// dynamically from the same `// federated.export` markers at build time.
// Run after adding/removing a federated.export marker (`qpq prep`).
import fs from 'fs';
import path from 'path';

import { scanFederatedExposes } from './federatedExports';
import { getAllViews } from './viewsWorkspace';

// Returns the number of federated aliases written.
export const writeFederatedTsconfigForApp = (root: string, appName: string): number => {
  const paths: Record<string, string[]> = {};
  let exposeCount = 0;

  for (const views of getAllViews(root, appName)) {
    const exposes = scanFederatedExposes(views.viewsDir);
    for (const [key, target] of Object.entries(exposes)) {
      // './Button' -> alias '@<app>/design-service-views/Button'
      const alias = `${views.alias}/${key.replace(/^\.\//, '')}`;
      // paths resolve against baseUrl (repo root, from tsconfig.base.json),
      // so entries stay root-relative regardless of where this file lives.
      const rel = path.join('apps', appName, 'services', views.service, 'views', target.replace(/^\.\//, '')).split(path.sep).join('/');
      paths[alias] = [rel];
      exposeCount++;
    }
  }

  const sorted = Object.fromEntries(Object.entries(paths).sort(([a], [b]) => a.localeCompare(b)));
  const outFile = path.join(root, 'apps', appName, 'tsconfig.federated.json');

  fs.writeFileSync(
    outFile,
    JSON.stringify(
      {
        // GENERATED by `qpq prep` — do not edit. Type aliases for federated
        // cross-view imports; runtime resolution is handled by module federation.
        extends: '../../tsconfig.base.json',
        compilerOptions: { paths: sorted },
      },
      null,
      2,
    ) + '\n',
  );

  return exposeCount;
};
